### PR TITLE
Cleaner named scans

### PR DESCRIPTION
**Pull request by flayisflay**
I like using your scanner for hackthebox, but found it's much easier to use the given name of the machine that I'm working on rather than using the ip address the whole way through.

This commit checks for the optional argument -n, then will set the ident variable to either the desired name, or the ip address if no name is given.

### CODE REVIEW

**Comment by flayisflay** [comment]
Fixed the config.json; Nope, i'm not working on it currently. You're free to merge.

**Comment by codingo** [comment]
Thank-you for this. I'll test and merge this on Monday - a bit time pressed today. Feel free to reply back if you don't hear anything by then.

**Comment by codingo** [comment]
@flayisflay looks like there's some dependancy cleanup to do on this since you merged back into the main project:

```
Traceback (most recent call last):
  File "./reconnoitre.py", line 9, in <module>
    from htb_scan import htb_scan
ImportError: No module named htb_scan
```

Removing the dependency has a flow on effect for the following error (when specifying a target range and no named host):
```
|"""\-=  RECONNOITRE
(____)      An OSCP scanner by @codingo_

[+] Testing for required utilities on your system.
[#] Performing service scans
Traceback (most recent call last):
  File "./reconnoitre.py", line 135, in <module>
    main()
  File "./reconnoitre.py", line 111, in main
    service_scan(arguments.target_hosts, ident, arguments.output_directory, '', arguments.quiet, arguments.quick, arguments.no_udp_service_scan)
  File "/opt/Network_Enumeration/Reconnoitre/reconnoitre/service_scan.py", line 93, in service_scan
    target_file(target_hosts, output_directory, ident, dns_server, quiet, quick, no_udp_service_scan)
TypeError: target_file() takes exactly 6 arguments (7 given)
```

**Comment by flayisflay** [comment]
Hey, sorry for the delay. Made a fix that should clear it up. If it doesn't, hand over a query that causes it to fail. Thanks!

**Comment by codingo** [comment]
Full plate for a few days but planning to review this on Wednesday. I'll tag and merge this so you can use it towards hacktoberfest also.

**Comment by codingo** [comment]
@flayisflay not ignoring this, but a bit buried. Planning to circle back very soon.

**Comment by codingo** [comment]
Just touching base to let you know that I'm not ignoring this. I've received quite a lot of pull requests over a few days (a great problem really!). Hoping to have everything up to date by Wednesday evening, but may not get to this until then.

**Comment by codingo** [comment]
@flayisflay just touching base to see where this landed? If you can push what you have I'll rebase it into the current master.

**Comment by flayisflay** [comment]
Hey,

I see that you changed the module structure. It's been a while since I looked at the code base, but it looks like enough has changed to where I'll have to make some changes. I'll try and issue an updated commit when I've got time.

Cheers

**Comment by codingo** [comment]
Much appreciated. I'm planning to do a rewrite of this over Hacktoberfest this year so it would be good to land this before then (so the logic can form a part of my planning process).

**Pull request closed without merging**
