### PR TITLE
Ping sweeper file handling

### PR DESCRIPTION
**Pull request by evcsec**
Updated the nmap command to handle file inputs for ping_sweeper function.
The function currently does not handle this input, but does handle IP ranges (i.e. 10.1.1.1-230).
The 'iL' flag allows for file specification for nmap to scan targets.

### CODE REVIEW

**Comment by evcsec** [comment]
I notice you've made some changes for this issue @codingo.
The fix I proposed was a few lines, but please close this if is unnecessary now :+1:

**Comment by codingo** [comment]
Reviewing this shortly. I'll resolve the conflict also :)

**Comment by codingo** [comment]
Conflict resolved, could you review and let me know if you're ok with a merge @evcsec?

**Comment by evcsec** [comment]
Changes are looking good @codingo.
Ran through some quick tests to ensure functionality and spotted a duplication of lines in --dns/--dnssweep. Updated the culprit line.

**Pull request merged**
