### PR TITLE
Code cleanup and automated PEP8 code style check (flake8)

### PR DESCRIPTION
**Pull request by pax0r**
Partially solves #52 

Mostly automatic code recaftor, but should help you keep with PEP8

### CODE REVIEW

**Comment by codingo** [comment]
Thank-you! I'll resolve conflicts for you shortly and merge.

**Comment by codingo** [comment]
Actually, if you don't mind @pax0r - could you resolve the conflicts here? If you compare to master you can see the folder structure change that broke  this pull request. I'll continue to tackle #61 in the meantime.

**Comment by pax0r** [comment]
I did it - FYI read https://www.python.org/dev/peps/pep-0008/ for better Python-like code style :) you can use tool flake8 to test code-style on your local machine too.

**Comment by codingo** [comment]
Thank-you. I am familiar with pep8 / python quite well, this is an old project of mine that's slowly getting a refactor (you can see better examples of this in https://github.com/codingo/vhostscan). Merging this over now but will likely replace these test cases in the future to mirror that of other projects of mine  for consistency.

**Pull request merged**
