### PR TITLE
Convert scan output to strings from bytes

### PR DESCRIPTION
**Pull request by yvonneKim**
Adds a conversion from bytes to strings for parsing the scan output. Before, it would give TypeErrors. 

This is my very first contribution to an open source project. Please let me know if there's something I've missed in this process.

### CODE REVIEW

**Comment by codingo** [comment]
Closes #45 

Will review this on Monday and merge after testing, a bit against the wall today.

And for your first contribution you've done great!

**Comment by codingo** [comment]
Just touching base to let you know that I'm not ignoring this. I've received quite a lot of pull requests over a few days (a great problem really!). Hoping to have everything up to date by Wednesday evening, but may not get to this until then.

**Comment by codingo** [comment]
Hi @yvonneKim, I've landed a few pull requests today so had to resolve conflicts on this branch. Could you please re-test your branch and let me know if you're happy for it to be merged to master?

**Comment by yvonneKim** [comment]
It looks good to me.

**Pull request merged**
